### ISSUE TITLE
undefined reference to symbol when building samples

### ISSUE THREAD

**Issue by NoyaFangzhou** [icnc/icnc#54]
I build TBB and CNC separately and specify the path to TBB library using the -DTBBROOT variable. When I build the sample programs, I encountered this error:

```
# Makefile command that raise this error:
g++ -pthread  -std=c++0x -O3  -o jacobi2D jacobi2D.o jacobi2D_cnc.o -L/localdisk/local/lib/intel64 -lcnc -lrt -ltbb -ltbbmalloc
```

```
# error message:

/bin/ld: warning: libtbb.so.12, needed by /localdisk/local/lib/intel64/libcnc.so, may conflict with libtbb.so.2
/bin/ld: jacobi2D.o: undefined reference to symbol '_ZN3tbb6detail2r126wait_bounded_queue_monitorEPNS1_18concurrent_monitorEmlRNS0_2d113delegate_baseE'
/bin/ld: /localdisk/local/lib64/libtbb.so.12: error adding symbols: DSO missing from command line
```

Any ideas?

**Comment by fschlimb** [comment]
> /bin/ld: warning: libtbb.so.12, needed by /localdisk/local/lib/intel64/libcnc.so, may conflict with libtbb.so.2

I suspect you are linking against a different TBB than the on used to build the CnC library. Make sure you use the identical TBB install for building your programs as used for building CnC itself.

**Comment by NoyaFangzhou** [comment]
@fschlimb Thanks for your suggestion! I rechecked my build and it seems that TBB creates multiple versions., as listed below 

```
libtbbbind_2_5.so.3    libtbbmalloc_proxy.so    libtbbmalloc_proxy.so.2.7  libtbbmalloc.so.2    libtbb.so     libtbb.so.12.7
libtbbbind_2_5.so  libtbbbind_2_5.so.3.7  libtbbmalloc_proxy.so.2  libtbbmalloc.so            libtbbmalloc.so.2.7  libtbb.so.12
```

When building CnC, we only provide the path to the TBB root and I do not know which version it uses.

**Comment by fschlimb** [comment]
The error message suggests CnC links against none of them: libtbb.so.__12__

**Comment by NoyaFangzhou** [comment]
@fschlimb  Thank you. This problem has been solved. TBB library has been put in lib64/ but the Makefile assumes the TBB should be found in lib/. Adding the path to TBB library in the Makefile can address this issue.
